version: "3.2"
services:
  db:
    image: ledgersmb/ledgersmb-dev-postgres
    container_name: postgres-lsmb-${LSMB_DEV_VERSION}-devel
    environment:
      POSTGRES_PASSWORD: abc
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  selenium:
    image: wernight/phantomjs:2.1.1
    container_name: selenium-${LSMB_DEV_VERSION}-devel
    command: phantomjs --webdriver=4422
    stop_signal: SIGKILL
    expose:
      - 4422
  lsmb:
    depends_on:
      - db
      - selenium
    image: ledgersmb/ledgersmb-dev-lsmb
    container_name: lsmb-${LSMB_DEV_VERSION}-devel
    links:
      - "db:postgres"
    volumes:
      - type: bind
        target: /srv/ledgersmb
        source: ${PWD}
    environment:
      LSMB_BASE_URL: http://lsmb-${LSMB_DEV_VERSION}-devel:5762
      LSMB_TEST_DB: 1
      LSMB_NEW_DB: lsmbtestdb
      POD_TESTING: 1
      REMOTE_SERVER_ADDR: selenium
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: abc


volumes:
  dbdata:

