version: "3.2"
services:
  mailhog:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
  db:
    image: ledgersmb/ledgersmb-dev-postgres
    environment:
      POSTGRES_PASSWORD: abc
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  selenium:
    image: wernight/phantomjs:2.1.1
    command: phantomjs --webdriver=4422
    stop_signal: SIGKILL
    expose:
      - 4422
    environment:
      LANG: en_US.UTF-8
  lsmb:
    depends_on:
      - db
      - selenium
      - mailhog
    image: ${LSMB_IMAGE:-ledgersmb/ledgersmb-dev-lsmb}
    links:
      - "db:postgres"
    volumes:
      - type: bind
        target: /srv/ledgersmb
        source: ${PWD}
    environment:
      LSMB_BASE_URL: http://proxy:80
      PSGI_BASE_URL: http://lsmb:5762
      LSMB_TEST_DB: 1
      LSMB_NEW_DB: lsmbtestdb
      COA_TESTING: 1
      REMOTE_SERVER_ADDR: selenium
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: abc
  proxy:
    image: ledgersmb/ledgersmb-dev-nginx
    expose:
      - 80
    depends_on:
      - lsmb
    volumes:
      - type: bind
        target: /srv/ledgersmb
        source: ${PWD}


volumes:
  dbdata:

